theme: jekyll-theme-minimal
title: "The Migration Experience: A Conceptual Framework and Systematic Review of Psychological Acculturation [Github Repository]"
#description: "Author Information:<br>██████ ██████████<br>█████ █████████<br>█████ ██████<br>█████ ██ █████<br>███ ███████<br>████████████████████<br><br>[Authors and other identifying information removed for blind review.]"
description: "Jannis Kreienkamp<br>Laura F. Bringmann<br>Raili Engler<br>Peter de Jonge<br>Kai Epstude<br>(University of Groningen)"
github: true
