theme: jekyll-theme-minimal
title: "Acculturation Review"
description: "Jannis Kreienkamp<br>Laura Bringmann<br>Raili Engler<br>Peter de Jonge<br>Kai Epstude<br>(University of Groningen)<br><br>[Authors and other identifying information will be removed for blind review.]"
