theme: jekyll-theme-minimal
title: "Acculturation Review"
description: "Author Information:<br>█████████████████<br>███████████████<br>████████████<br>██████████████<br>███████████<br>█████████████████████████<br><br>[Authors and other identifying information removed for blind review.]"
# description: "Jannis Kreienkamp<br>Laura Bringmann<br>Raili Engler<br>Peter de Jonge<br>Kai Epstude<br>(University of Groningen)"
