---
title: "Acculturation Scales Database"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(crosstalk)
library(dplyr)

quakes$class <- factor(floor(quakes$mag), labels = c("Light", "Moderate", "Strong"))
set.seed(10101)
quakes <- quakes %>% sample_n(200)
sd <- SharedData$new(quakes)
```

Inputs {.sidebar}
-----------------------------------------------------------------------

```{r}
filter_slider("mag", "Magnitude", sd, ~mag, step = 0.1)
filter_slider("depth", "Depth", sd, ~depth)
```

Row 1
-----------------------------------------------------------------------

### Map

```{r}
library(d3scatter)
shared_mtcars <- SharedData$new(mtcars)
bscols(widths = c(3,NA,NA),
  list(
    filter_checkbox("cyl", "Cylinders", shared_mtcars, ~cyl, inline = TRUE),
    filter_slider("hp", "Horsepower", shared_mtcars, ~hp, width = "100%"),
    filter_select("auto", "Automatic", shared_mtcars, ~ifelse(am == 0, "Yes", "No"))
  ),
  d3scatter(shared_mtcars, ~wt, ~mpg, ~factor(cyl), width="100%", height=250),
  d3scatter(shared_mtcars, ~hp, ~qsec, ~factor(cyl), width="100%", height=250)
)
```

### Scatter

```{r}
library(plotly)
plot_ly(sd) %>%
  add_markers(x = ~depth, y = ~stations, color = ~class, mode = "markers") %>%
  layout(dragmode = "select")
```

Row 2
-----------------------------------------------------------------------

### Table

```{r}
library(DT)
datatable(sd, rownames = FALSE, extensions = 'Scroller', options = list(
  scrollY = 200,
  scroller = TRUE
))
```

