---
title: "Untitled"
format: html
editor: visual
---

## Load Data

```{r}
#| label: load data

# load libraries
library(dplyr)
library(stringr)
library(purrr)
library(bib2df)
library(tools)

# convert .RData -> .rdb/.rdx
tools:::makeLazyLoadDB(local({load("data/wrangled.RData"); environment()}), "data")
lazyLoad("data")

```

## Citations

```{r}
#| label: get used citation keys from aux

# read aux file
aux <- readLines("Citation Statement/main.aux")

# extract citation keys
main_keys <- str_extract_all(aux, "\\{([^\\},\\/\\s[[:punct:]]]{4,})(?:,\\s*([^\\},]+))*\\}") %>% 
  unlist %>%
  str_extract_all(., ".*[[:digit:]].*") %>%
  unlist %>%
  gsub('^.|.$', '', .) %>%
  unique
  
```

```{r}
#| label: citation subsetting

# import full reference bib
mybib <- bib2df::bib2df("references.bib")

# filter and export bib from manuscript
mybib_main <- mybib %>%
  filter(BIBTEXKEY %in% main_keys) %>%
  distinct(., BIBTEXKEY, .keep_all = TRUE)
bib2df::df2bib(mybib_main, file = "references_main.bib", append = FALSE)

# filter and export theoretical
mybib_theoretical <- mybib %>%
  filter(BIBTEXKEY %in% unique(dt.Theories.Included$CitationKey)) %>%
  distinct(., BIBTEXKEY, .keep_all = TRUE)
bib2df::df2bib(mybib_theoretical, file = "references_theoretical.bib", append = FALSE)

# filter and export psychometric
mybib_psychometric <- mybib %>%
  filter(BIBTEXKEY %in% unique(dt.Scales.Included$CitationKey)) %>%
  distinct(., BIBTEXKEY, .keep_all = TRUE)
bib2df::df2bib(mybib_psychometric, file = "references_psychometric.bib", append = FALSE)

# filter and export empirical
mybib_empirical <- mybib %>%
  filter(BIBTEXKEY %in% unique(dt.Empirical.included$CitationKey)) %>%
  distinct(., BIBTEXKEY, .keep_all = TRUE)
bib2df::df2bib(mybib_empirical, file = "references_empirical.bib", append = FALSE)

# Re-Export Directory Data without rerunning full supplemental
save(dt.Scales, dt.Scales.Included, dt.Theories, dt.Theories.Included, file = "data/AcculturationScales.RData")
  
```
